[package]
name = "nx-skel"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
nx-bone = { workspace = true }
nx-common = { workspace = true }

byteorder = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }

[dev-dependencies]
nx-test = { workspace = true }

tokio = { workspace = true, features = ["rt", "macros"]}

[features]
serde = ["dep:serde", "nx-common/serde"]
