[package]
name = "nx-cli"
version = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "nx-cli"
path = "src/main.rs"

[dependencies]
nx-anim = { workspace = true, features = ["serde"] }
nx-common = { workspace = true, features = ["clap", "serde"] }
nx-crc = { workspace = true }
nx-qb = { workspace = true, features = ["serde"] }
nx-stdkey = { workspace = true, features = ["serde"] }
nx-skel = { workspace = true, features = ["serde"] }

clap = { workspace = true }
color-eyre = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
